### ISSUE TITLE
HTTPRequest Error Status 401

### ISSUE THREAD

**Issue by KerlinerBindl** [Eunanibus/MMM-HTTPRequestDisplay#1]
hey, in every xml file i used there was an issue. it shows 
HTTP Request Failed. Status 401

**Comment by Eunanibus** [comment]
Hi. Thanks for your comment. I'm aware of an issue where any requests to XML outside of the domain are rejected. This issue is currently being worked on and a new update will be released within the next month or so.

**Comment by ac1dphr3aq** [comment]
IT DOESN'T WORK EUNAN!

**Comment by martinsirbe** [comment]
@KerlinerBindl it seems like you are trying to access some resource that requires an authentication as HTTP 401 means that the HTTP request failed because it was unauthorized, you can read more about this here https://httpstatuses.com/401
Maybe you can share the link?

**Comment by Eunanibus** [comment]
This is due to cross site scripting or CORS (Cross origin request). I'm aware of it. It will be resolved when I get the opportunity. A temporary fix can be that if you are running your own local server page is to enable this.
