### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by BeatIdo** [Eunanibus/MMM-HTTPRequestDisplay#2]
Hi I tried to add a user authentication as next parameter in XMLHttpRequest.open call.

``http.open("GET", this.config.httpRequestURL, true, 'myapikey');``

I'm still getting error status 0 for the moment.
The key is valid if used this way in a browser http://key@apiURL

Do you intend to support API key parameter in your module ?

**Comment by Eunanibus** [comment]
Apologies for late reply and minimal updating. Commitments have kept me incredibly busy recently. This project needs a major update which is being planned soon, as there are a few issues with cross-site scripting I need to address. But yes, adding a basic API key parameter is something I will implement. I intend to complete and update this project before the end of July with any luck.
